#ifndef TMTCDBMANAGERLIB_GLOBAL_H
#define TMTCDBMANAGERLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TMTCDBMANAGERLIB_LIBRARY)
#  define TMTCDBMANAGERLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TMTCDBMANAGERLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TMTCDBMANAGERLIB_GLOBAL_H
