#ifndef SC2KMANAGER_GLOBAL_H
#define SC2KMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SC2KMANAGER_LIBRARY)
#  define SC2KMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SC2KMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SC2KMANAGER_GLOBAL_H
